# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Core Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 pytest
        sudo apt-get update && sudo apt-get install unzip openjdk-19-jdk graphviz-dev -y
        pip install -e . && pyjoern --install
        /home/runner/work/pyjoern/pyjoern/pyjoern/bin/joern-cli/joern-parse /home/runner/work/pyjoern/pyjoern/tests/source/simple.c

    - name: Pytest
      run: |
        pytest ./tests/tests.py
